//
//  CarsRegistered .swift
//  Car Rent (Beeline)
//
//  Created by user on 18.05.2022.
//

import Foundation

class Cars {
    static let allCars: [Car] = [
        Car(name: "Nissan Versa",
            pricePerDay: 93,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2020-nissan-versa-101-1555093621.jpg?crop=0.872xw:0.736xh;0.0353xw,0.219xh&resize=1200:*",
            rating:8,
            overview: "The 2022 Nissan Versa sedan is a fine transportation tool for getting passengers from point A to point B, but it also makes the journey more enjoyable than many other subcompact cars. Not only is the Nissan handsome, it has a price tag that's affordable for almost everyone. While almost everyone will also find its four-cylinder engine to be ill-equipped for prompt highway passes, they should find its highway fuel economy to be impressive. The Versa's smooth ride and cushy front seats make it a relaxing chariot for daily commutes, and it's available with more driver assists than its classmates. Although some of those alternatives are better to drive, the 2022 Versa is a very good little car for folks who care most about comfort and safety.",
            size: .compact,
            color: .red,
            style: .sedan
           ),
        Car(name: "Kia Rio",
            pricePerDay: 78,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/17980-2022-rio-5-door-1638309744.jpg?crop=1.00xw:0.849xh;0,0.0505xh&resize=1200:*",
            rating: 9,
            overview: "The Kia Rio represents cheap, simple transportation at its best. Fuel efficient and inexpensive but with a surprising amount of driving sophistication and features for the price, this subcompact provides good value for the money. It’s available as either a sedan or a hatchback, but neither body style has much space in the rear seat or cargo area. Apple CarPlay and Android Auto are standard equipment, and several driver-assistance features are optional. Now that many of its competitors—including the Chevy Sonic, Honda Fit, and Toyota Yaris—have left the marketplace, the Rio is one of the last truly cheap new cars left, and it’s good enough to earn a spot on our 2022 Editors' Choice list.",
            size: .compact,
            color: .red,
            style: .sedan
           ),
        Car(name: "Honda Civic",
            pricePerDay: 125,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2022-honda-civic-sedan-110-1623810388.jpg?crop=0.796xw:0.673xh;0.0817xw,0.219xh&resize=1200:*",
            rating: 9.5,
            overview: "Honda's popular Civic compact car gets a big glow-up for the 2022 model year as it debuts a more grown-up appearance, new features, and a refined cabin design. The improvements and more helped it earn a spot on our Editors' Choice list. A selection of four-cylinder engines—including a turbocharged 1.5-liter—are offered; front-wheel drive will continue to be standard as Honda insists all-wheel drive is not part of the plan. Updated tech features such as a larger infotainment display, wireless smartphone connectivity, and improved driver-assistance features are all meaningful updates that will help the Civic stave off competition from the likes of the Hyundai Elantra, the Mazda 3, and the Toyota Corolla.",
            size: .compact,
            color: .white,
            style: .sedan
           ),
        Car(name: "Toyota Corolla",
            pricePerDay: 99,
            isAvailable: false,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2022-corollaxse-celestite-0009-1500x1000-1641929279.jpg?crop=0.824xw:0.695xh;0.107xw,0.0986xh&resize=1200:*",
            rating: 8,
            overview: "The 2022 Toyota Corolla exists as an affordable and attractive compact car that's loaded with standard active safety features. While alternatives such as the Honda Civic and Mazda 3 are more fun to drive, the Corolla has a comfortable ride quality and sporty models of its own. As with many of its compact competitors, the Toyota is offered as a sedan or a hatchback. Both have distinctive designs, but uncharacteristically the hatch has a smaller back seat and less cargo space than the sedan. Select models can be had with a manual transmission, and the sedan offers an exceptionally fuel-efficient hybrid powertrain. Unfortunately, every model comes with a coarse-sounding engine. Still, the 2022 Corolla continues to be a popular choice, especially among shoppers who prioritize style and safety.",
            size: .compact,
            color: .blue,
            style: .sedan
           ),
        Car(name: "Honda Accord",
            pricePerDay: 129,
            isAvailable: false,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2021-honda-accord-hybrid-mmp-1-1634840672.jpg?crop=1.00xw:0.842xh;0,0.115xh&resize=1200:*",
            rating: 10,
            overview: "Although SUVs and crossovers are the people haulers these days, we think those folks are missing out by not considering the superb 2022 Honda Accord sedan. The Accord can do most things your average compact crossover can do, and its spry handling will give its driver more of a thrill should they encounter a twisty road. Two turbocharged engines are offered, as is a hybrid powertrain that provides a more efficient twist on the daily commute. With a commodious trunk and enough space for four adults to relax in comfort, the Accord is also an ideal road-trip partner, made even better by its comprehensive set of standard driver-assistance features and intuitive infotainment system. There's a reason the Accord makes our 2022 10Best and Editors' Choice lists like it has done time and time again: It's a winner.",
            size: .medium,
            color: .white,
            style: .sedan
           ),
        Car(name: "Nissan Altima",
            pricePerDay: 150,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2019-nissan-altima-3-1548450534.jpg?crop=0.909xw:0.767xh;0.0673xw,0.154xh&resize=1200:*",
            rating: 8,
            overview: "The 2022 Nissan Altima is a wholly competent mid-size sedan that fills the void between the less and more desirable alternatives in the segment. The Nissan isn't as holistically excellent as the Honda Accord nor is it as ho-hum as the VW Passat. Instead, the Altima is notable for its attractive styling, comfortable cabin, and surprising athleticism. Its available all-wheel-drive system is a popular option, even though its added capability is far from necessary. All-wheel drive, however, is only compatible with the Altima’s unremarkable standard four-cylinder powertrain—so those buyers also tempted by the more powerful VC-Turbo engine option are out of luck. Despite not offering a hybrid or plug-in-hybrid model like other family sedans, every Altima is notably fuel efficient. Combine that with its other pleasant characteristics and you get a good car that most folks will appreciate.",
            size: .medium,
            color: .white,
            style: .sedan
           ),
        Car(name: "Ford Mustang",
            pricePerDay: 300,
            isAvailable: false,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2024-ford-mustang-rendering-1652121017.jpg?crop=0.801xw:0.675xh;0.114xw,0.202xh&resize=1200:*",
            rating: 10,
            overview: "The Ford Mustang is easily one of the most iconic and recognizable cars of all time. It kick-started the pony-car class in the mid-1960s and has been democratizing performance for generations of Americans ever since. But while the future of its competitors, the Chevy Camaro and the Dodge Challenger, looks in doubt, the Mustang is set to receive an all-new generation in the next few years—the seventh since the pony car debuted in 1964. There has not been much yet in the way of official information from Ford, but Mustang prototypes have been spied testing, showing rakish bodywork and an athletic stance. The Mustang should continue with a range of internal-combustion engines, but don’t be surprised to see a hybrid or even electric version down the line.",
            size: .full,
            color: .yellow,
            style: .coupe
           ),
        Car(name: "Audi A5",
            pricePerDay: 350,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2020-audi-a5-coupe-101-1567777441.jpg?crop=0.764xw:0.702xh;0.170xw,0.233xh&resize=1200:*",
            rating: 7.5,
            overview: "Style mavens will find the 2022 Audi A5 coupe and Cabriolet convertible models more eye-catching than the A4 sedan while pragmatists will be happy to know they require few compromises to practicality. Both A5 body styles are sophisticated, upscale, and athletic, making them a great choice for luxury buyers who also enjoy driving. The coupe and convertible are both powered by a gutsy 261-hp turbocharged four-cylinder paired with standard all-wheel drive. Those looking for more oomph should consider upgrading to the Audi S5 (reviewed separately) or perhaps the BMW 440i, but most drivers will find the 2022 A5's powertrain to be plenty potent for even spirited driving.",
            size: .full,
            color: .green,
            style: .coupe
           ),
        Car(name: "BMW X6",
            pricePerDay: 400,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2020-bmw-x6-xdrive40i-126-1583153962.jpg?crop=0.699xw:0.589xh;0.0785xw,0.387xh&resize=1200:*",
            rating: 9,
            overview: "The BMW X6 is like Don Corleone, which is to say it's the godfather of coupelike SUVs. The original that debuted back in the late 2000s basically invented the controversial breed, which spawned imitators from the likes of Audi and Mercedes-Benz. While beauty is in the eye of the beholder when it comes to these polarizing crossover coupes, the sloped-back Bimmer boasts a pair of sublime engines: a 335-hp inline-six-cylinder (40i) and a 523-hp twin-turbo V-8 (M50i). Thrill seekers will want the latter, but it comes with a hefty price. Both mills are mated to an automatic transmission that's as smooth as they are. Peak performance is offered on the six-figure X6 M (reviewed separately), but even the less extreme models are entertaining to drive. The regular X5 is more upright and practical, but the 2022 BMW X6 is just as luxurious inside and better suited for extroverts.",
            size: .full,
            color: .white,
            style: .coupe
           ),
        Car(name: "Porsche 911",
            pricePerDay: 1000,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2022-porche-911-gts-47-1632250920.jpg?crop=0.843xw:0.712xh;0.159xw,0.185xh&resize=1200:*",
            rating: 10,
            overview: "With transcendent driving traits and terrific twin-turbo flat-six engines, the 2022 Porsche 911 is a nearly flawless sports car, and it's an obvious Editors' Choice winner. Apart from being too expensive for most enthusiasts, Porsche's iconic two-plus-two-seater is as immersive as it is versatile. Along with the aforementioned flat-six which produces a distinctive snarl and makes between 379 and 473 horsepower­­–we review the higher-powered GT3 and Turbo variants separately­–the lineup offers a quick-shifting dual-clutch automatic or a manual transmission and rear- or all-wheel drive. The latter ensures its incredible performance can be enjoyed in all four seasons. The 911 comes in coupe, cabriolet (read: convertible), or quasi-convertible Targa body styles. The beauty of the 911 is that its athleticism doesn't diminish its livability. Its ride is surprisingly civil considering its cornering limits and race car-like steering feel. Its interior is roomy up front and can be lavishly appointed. And its driver is treated to a satisfyingly low seating position but also excellent outward visibility.",
            size: .medium,
            color: .red,
            style: .sportsCar
           ),
        Car(name: "Mazda MX-5 Miata",
            pricePerDay: 300,
            isAvailable: false,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2022-mazda-mx-5-miata-mmp-1-1639659696.jpg?crop=1.00xw:0.924xh;0,0.0262xh&resize=1200:*",
            rating: 9,
            overview: "Few cars deliver driving thrills at an affordable price quite like the 2022 Mazda MX-5 Miata, and it's the only affordable sports car with a convertible top. It's also on our 2022 Editors' Choice list. A spunky four-cylinder primarily pairs with a satisfying six-speed manual, but an automatic transmission is offered, too. The Miata's handling is eager and playful, which makes encountering twisty roads a joyful experience. Most versions come with a manually-folding soft-top, but there's a more expensive RF model available with a power-folding Targa hardtop. With either roof, the Miata's interior is snug but nicely equipped, with infotainment features such as Apple CarPlay and Android Auto standard across all trims.",
            size: .medium,
            color: .black,
            style: .sportsCar
           ),
        Car(name: "Ferrari 488 Pista",
            pricePerDay: 3000,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2019-ferrari-488-pista-125-1528476287.jpg?crop=0.653xw:0.596xh;0.241xw,0.404xh&resize=1200:*",
            rating: 10,
            overview: "The 2020 Ferrari 488 Pista is the stuff of supercar dreams. Broad-shouldered with bulging fenders and a graceful arch of a roof, this confident Italian stands out in a crowd. Its cabin is surprisingly spacious, offering more real estate than you typically find in a two-door sports car. When it comes to performance, the 488 provides the power and poise you'd expect from a car crafted by the legendary Ferrari nameplate. It rockets from a standstill to 60 mph in less than three seconds, and it whips through corners and barrels down straightaways with singular agility. This Ferrari costs about as much as a home in the suburbs, but if you have the means, it has the goods to thrill and excite.",
            size: .medium,
            color: .red,
            style: .sportsCar
           ),
        Car(name: "Volkswagen Golf",
            pricePerDay: 250,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2021-volkswagen-golf-mmp-1-1604508183.jpg?crop=0.814xw:0.688xh;0.175xw,0.255xh&resize=1200:*",
            rating: 9,
            overview: "Few compact hatchbacks are better than the 2021 Volkswagen Golf, but one that is happens to share the same showroom: the sporty GTI (reviewed separately). Apart from the standard Golf's lower asking price and higher fuel efficiency, it isn't as desirable as its more powerful, better-equipped sibling. While that's partly why VW will only offer the next-generation GTI and high-performance Golf R on our shores, it doesn't diminish that the regular version remains a terrific value in its final year. Despite a small and underpowered turbo-four engine, it boasts an excellent six-speed manual or eight-speed automatic transmission. It has a great chassis that provides athletic handling and a composed ride. And it offers a surprisingly roomy interior along with a large cargo hold. The boxy Golf isn't as eye-catching or feature-laden as many compact rivals, but overall it's much more gratifying than meets the eye and an Editors' Choice winner.",
            size: .compact,
            color: .blue,
            style: .hatchback
           ),
        Car(name: "Audi A7",
            pricePerDay: 700,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2019-audi-a7-3-0t-108-1539199412.jpg?crop=0.721xw:0.662xh;0.221xw,0.338xh&resize=1200:*",
            rating: 9,
            overview: "From its sleek fastback design to its refined driving manners, the 2022 Audi A7 is a smooth operator. Audi discreetly hides a hatchback within its fastback profile that makes it more practical than other mid-size luxury sedans such as its corporate counterpart, the A6 sedan, or rivals such as the Mercedes-Benz CLS450. While the A7's racy roofline intrudes on rear-seat headroom, the rest of its cabin is beautifully appointed and packed with state-of-the-art tech. Its 335-hp turbocharged V-6 teams with an unobtrusive dual-clutch automatic transmission and all-wheel drive. This polished powertrain makes the handsome hatch sneaky quick, but we wish it included a more exciting soundtrack. A plug-in-hybrid version also improves the lineup's green cred. While all passengers will appreciate its tranquil ride quality, the driver will also enjoy its adroit handling and excellent outward visibility. The 2022 A7 isn't perfect, but its prettiness and practically help put it near the top of its class and on our Editors' Choice list.",
            size: .full,
            color: .black,
            style: .hatchback
           ),
        Car(name: "Kia Stinger",
            pricePerDay: 200,
            isAvailable: false,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2022-kia-stinger-202-1615916952.jpg?crop=0.731xw:0.618xh;0.128xw,0.293xh&resize=1200:*",
            rating: 8.5,
            overview: "Kia's big sports sedan—the 2022 Stinger—aims high to challenge the automotive elites from Europe, and nearly pulls it off. When compared with rivals such as the Audi A5 Sportback and the BMW 4-series Gran Coupe, the Stinger offers a very similarly premium look and feel as well as lots of driving verve, making it a great option for enthusiasts on a budget. It shares its underpinnings with the impressive Genesis G70 sedan, but the Stinger disguises its roomier interior, larger cargo hold, and hatchback liftgate with a sexy fastback roofline. A pair of turbocharged engines are offered: a 300-hp turbocharged 2.5-liter four-cylinder is standard and a gutsy 368-hp twin-turbo V-6 is available. Rear-wheel drive is standard but all-wheel drive is also available for those who want it.",
            size: .full,
            color: .black,
            style: .sedan
           ),
        Car(name: "Mazda MX-5 Miata RF",
            pricePerDay: 530,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/17q1/674167/2017-mazda-mx-5-miata-rf-first-drive-review-car-and-driver-photo-674193-s-original.jpg?fill=2:1&resize=980:*",
            rating: 9.5,
            overview: "For 28 years, the Mazda MX-5 Miata has adhered to Mazda’s oft-cited jinba-ittai ethos, a Japanese phrase drawn from samurai horse archery that translates to “horse and rider as one.” The purity of connection required to accurately shoot arrows astride a moving animal, as distilled into an automobile, makes for a light, simple, and fantastic sports car. Also, horses don’t have roofs and neither do Miatas, if you’re doing it right. Mazda has never built a true Miata coupe, the closest examples being a couple of Japan-market fixed-hardtop conversions and the Power Retractable Hardtop (PRHT) introduced on the previous, NC generation. Perhaps the closest yet is the sexpot MX-5 Miata RF we just drove, even if it really is an extension of the PRHT branch of the family tree. To put a finer point on the RF, its closest current analogue just might be the far pricier Porsche 911 Targa, being a demi-convertible with a similarly functioning top mechanism.",
            size: .compact,
            color: .red,
            style: .convertible
           ),
        Car(name: "Porsche 911 Targa 4 GTS",
            pricePerDay: 925,
            isAvailable: false,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/17q2/678295/2018-porsche-911-targa-4-gts-first-drive-review-car-and-driver-photo-682835-s-original.jpg?fill=2:1&resize=980:*",
            rating: 9,
            overview: "If you’ve driven along the edge of Donner Lake in Truckee, California, anytime in the past 15 years, you’ve noticed that turbocharged, all-wheel-drive automobiles parked along the side of the road aren’t exactly an uncommon sight. The Euer Saddle, marked as Donner Summit on I-80, sits at an elevation of 7239 feet and the lake itself at 5936. To the south, Echo Summit on Highway 50 reaches 7382 feet, while the Carson Pass on State Route 88 hits 8574. Even Reno, just down the mountain—and the former home of Porsche’s North American arm—lies at a 4505-foot elevation, not a whole lot lower than Denver. Up there, forced induction is a must to maintain performance in the thin air. Donner Pass also holds the distinction of being one of the snowiest places in the country, at least when California isn’t suffering from a drought. Until recently, the only Porsche 911 perfectly suited to the high-altitude sports-car mission was the extra-spendy 911 Turbo, which has featured four driven wheels since the end-of-the-aircooled-era 993 generation. Now, of course, every 911 except for the GT3 has a pair of charge-enhancing snails bolted to its flat-six engine. We predict a lot of 997 and 991.1 Carrera 4 models will find themselves listed on Reno/Tahoe’s Craigslist in short order, with a number of them, undoubtedly, replaced with a 2018 911 Targa 4 GTS.",
            size: .medium,
            color: .red,
            style: .convertible
           ),
        Car(name: "Hyundai Kona",
            pricePerDay: 99,
            isAvailable: false,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2022-hyundai-kona-n-line-awd-371-1635740332-mmp-1-1635778298.jpg?crop=0.936xw:0.988xh;0.0369xw,0.0120xh&resize=1200:*",
            rating: 9,
            overview: "When an SUV delivers as crisp a driving experience as the 2022 Hyundai Kona, it's hard to get hung up on the usual anti-crossover sentiment—so we won't. The subcompact Kona is, simply put, a great package that blends carlike on-road behavior with bold styling, a dose of practicality, and an elevated driving position; we like it so much we gave it an Editors' Choice award. Two four-cylinder engines are offered: a 2.0-liter four, which is admittedly pretty poky, and a more desirable turbocharged 1.6-liter four that delivers a lot more punch. Sticking to Hyundai's value-forward approach, the Kona comes with a long list of standard features which only grows as you move through the more expensive trims—the top few of which get downright posh. The Kona is one of the smaller offerings in the subcompact SUV segment, so it gives up cargo and passenger space to some of its larger rivals, but we think the trade-off for the Hyundai's compact package and fun-to-drive nature more than makes up for those shortcomings",
            size: .compact,
            color: .white,
            style: .suv
           ),
        Car(name: "Chevrolet Tahoe",
            pricePerDay: 370,
            isAvailable: false,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2022-chevrolet-tahoe-rst-101-1632768222.jpg?crop=0.599xw:0.505xh;0.242xw,0.120xh&resize=1200:*",
            rating: 9,
            overview: "The 2022 Chevy Tahoe is about as versatile as large SUVs come, with minivan-like passenger accommodations and pickup-rivaling towing capabilities, which earned it an Editors' Choice award. Chevy's second largest three-row ute—the separately reviewed Suburban is the first­—offers three engine options: a standard 355-hp V-8, a stouter 420-hp V-8, and a diesel six-cylinder with a stump-pulling 460 pound-feet of torque. The Tahoe's diverse trim levels include the rugged Z71 for tackling rough terrain and the more glamorous High Country. Too bad the latter costs as much as premium alternatives, such as the Cadillac Escalade and Lincoln Navigator, but it's not nearly as luxurious. The Tahoe's polarizing mug might push some shoppers into the GMC Yukon, but the rest will respect its popular tech features and impressively quiet cabin.",
            size: .full,
            color: .brown,
            style: .suv
           ),
        Car(name: "Honda Odyssey",
            pricePerDay: 190,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2021-honda-odyssey-393-1598917040.jpg?crop=0.788xw:0.663xh;0.0570xw,0.295xh&resize=1200:*",
            rating: 9,
            overview: "The 2023 Honda Odyssey will make you forget any negative thoughts about minivans once you experience its refined ride, solid handling, and quick-accelerating V-6 engine. Don’t worry—if a minivan is on your shopping list because you need practicality, the Odyssey won’t disappoint there either. Its novel Magic Seat system allows you to position the second row seats in a variety of ways—including a configuration that’ll keep feuding kiddies appropriately separated. The third row disappears into a recess in the floor to allow for more cargo space. The cabin isn’t as well connected and tech-focused as those in rivals such as the Chrysler Pacifica or Kia Carnival, but the Honda’s infotainment suite offers more than just the necessities, including an optional rear-seat entertainment system to keep the youngsters occupied.",
            size: .medium,
            color: .white,
            style: .minivan
           ),
        Car(name: "Chrysler Pacifica",
            pricePerDay: 134,
            isAvailable: true,
            imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2022-chrysler-pacifica-hybrid-mmp-1-1633376456.jpg?crop=0.801xw:0.674xh;0.149xw,0.158xh&resize=1200:*",
            rating: 9,
            overview: "When an SUV delivers as crisp a driving experience as the 2022 Hyundai Kona, it's hard to get hung up on the usual anti-crossover sentiment—so we won't. The subcompact Kona is, simply put, a great package that blends carlike on-road behavior with bold styling, a dose of practicality, and an elevated driving position; we like it so much we gave it an Editors' Choice award. Two four-cylinder engines are offered: a 2.0-liter four, which is admittedly pretty poky, and a more desirable turbocharged 1.6-liter four that delivers a lot more punch. Sticking to Hyundai's value-forward approach, the Kona comes with a long list of standard features which only grows as you move through the more expensive trims—the top few of which get downright posh. The Kona is one of the smaller offerings in the subcompact SUV segment, so it gives up cargo and passenger space to some of its larger rivals, but we think the trade-off for the Hyundai's compact package and fun-to-drive nature more than makes up for those shortcomings",
            size: .full,
            color: .blue,
            style: .minivan
           )
    ]
}
